listing/config/routes.rb
Rails.application.routes.draw do
  mount Datadisplay::Engine, at: "/display"

  resources :users
  resources :books

  root to: 'books#index'
end

listing/app/models/book.rb
class Book < ActiveRecord::Base
end

listing/app/models/user.rb
class User < ActiveRecord::Base
end

listing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

listing/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

listing/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :address)
    end
end

listing/app/helpers/application_helper.rb
module ApplicationHelper
end

listing/app/helpers/books_helper.rb
module BooksHelper
end

listing/app/helpers/home_helper.rb
module HomeHelper
end

listing/app/helpers/users_helper.rb
module UsersHelper
end

listing/app/views/books/_form.html.erb
<%= form_for(@book, class: "form") do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description, class: "control-label" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Back", books_path, class: "btn btn-default" %>
  </div>
<% end %>

listing/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

listing/app/views/books/index.html.erb
<h1>Listing Books</h1>
<table class = 'table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Display Table', datadisplay_path(type: "Book"), class: 'btn btn-primary' %>
<%= link_to 'New Book', new_book_path, class: 'btn btn-primary' %>

listing/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

listing/app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary" %>
<%= link_to 'Back', books_path, class: "btn btn-default" %>

listing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container">
    <div class = "text-left page-header well row">
      <h4 class = "col-md-5 col-sm-4 col-xs-4">Display Data</h4>
    </div>
    <% if notice %>
      <div class="alert alert-success">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
    <div>
      <ul class = "nav nav-tabs bg-inverse">
        <li class = "nav-item <%= "active" if current_page?(books_path) || current_page?(root_path) %>">
          <%= link_to "Books", books_path, class: "nav-link"%>
        </li>
        <li class = "nav-item <%= "active" if current_page?(users_path) %>">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class = "row">
      <div class = "col-md-12 col-sm-12 col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

listing/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

listing/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

listing/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user, class: 'btn btn-primary'%></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Display Table', datadisplay_path(:type => "User"), class: 'btn btn-primary' %>
<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

listing/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

listing/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>